### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by taiBsu** [mkaczanowski/pastebin#27]
Hi, 
I was trying to make the docker image running by using docker-compose:

```
version: "3"

services:
  pastebin:
    image: mkaczanowski/pastebin
    container_name: pastebin
    ports:
      - "8023:8000" # since 8000 is already taken on my side
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    external: true
```

However, after running `docker-compose up` the container just quits after a couple of seconds without outputting anything.

Same for running `docker pull mkaczanowski/pastebin` and `docker run --network host mkaczanowski/pastebin --address localhost --port 8000`.

Is this an image-side issue or on my side?

Best, taiBsu
